// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kprdrzylffyiwaiqfzcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwcmRyenlsZmZ5aXdhaXFmemNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDUwMDMsImV4cCI6MjA3MDQyMTAwM30.oP44JCnNcNliH0k9P7s5pbH5ycNdfeUJzfjwtGLmKTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});