// This file is automatically generated. Do not edit it directly.

// We are consolidating the Supabase client initialization to `src/lib/supabaseClient.ts`.
// This file is now re-exporting the client from there to maintain compatibility with existing imports.
export { supabase, hasSupabase } from '@/lib/supabaseClient';
